### ISSUE TITLE
Support forge

### ISSUE THREAD

**Issue by dakra** [magit/orgit#24]
Would be nice if I could store a link to a PR/issue/comment/etc.

**Comment by tarsius** [comment]
I pushed a quick draft to the ~forge~ branch, but it will likely be a while until I get back to that.

**Comment by tarsius** [comment]
There are a few things to be considered:

1. I cannot add anything like this to `orgit.el` because then that would start depending on `forge`. I could add either `orgit-forge.el` here or `forge-orgit.el` to `forge` though.
2. I don't really want to do that because now that `forge` has been released `orgit` should start using some of the information that `forge` can automatically determine based on its own configuration instead of requiring duplication in `orgit-export-alist`.
3. There's also `magit-bookmark.el`, which also does links, but differently with different hardcoded defaults.
4. Once I have implemented `git-handler.el` linking to blobs will be trivial and not require any special support. Regular file links will do.
5. All this should be restructured, but I don't know how exactly yet. Merge everything into Magit? Except Forge of course. But how about the low-level stuff that makes it unnecessary to set things explicitly? Can some of that be moved to Magit too, without that needing access to forge APIs?

This will be a lot of work and take a long time. I don't want to implement any intermediate versions that I am already fairly certain will go away eventually. So I have decided not to add any support for `forge` buffers to `orgit`.

**Comment by tarsius** [comment]
I have published the `orgit-forge` package.

Maybe I will do the things I mentioned above eventually as well, but now I am even less in a hurry. Also I do not intend to extend `orgit-forge` itself. But I do find that one feature that it does provide useful so I'll let you use that too. :stuck_out_tongue_winking_eye:

**Comment by ivanhjc** [comment]
I'm looking for a link method to magit blobs and so far the closest I can get is using `orgit-rev`, e.g.

     [[orgit-rev:d:/projects/jekyll/::bcaf878b65d6349da9e53ad9243796e72797c0db][Jekyll (rev bcaf878b6)]]

But what I want is to link to a file at a certain commit (called a blob as I understand) at a certain line or string. Is this now supported? I see you said 

> 4. Once I have implemented git-handler.el linking to blobs will be trivial and not require any special support. Regular file links will do.

But I couldn't find where this `git-handler` is.

**Comment by kyleam** [comment]
> But I couldn't find where this `git-handler` is.

See https://github.com/magit/magit/issues/2958

**Comment by ivanhjc** [comment]
@kyleam So this hasn't been implemented right?

**Comment by tarsius** [comment]
Right, and I still plan to implement it.
