### ISSUE TITLE
Cannot store any link with recent org

### ISSUE THREAD

**Issue by xzz53** [magit/orgit#32]
Any attempt to store a link result in an error, with the following message: `orgit-rev-store-1: Symbol’s function definition is void: org-link-store-props`.

Relevant package versions:
org: 20190715
org-plus-contrib: 20190715
orgit: 20190630.1351
magit: 20190630.1351

**Comment by xzz53** [comment]
Looks like replacing `org-link-store-props` with `org-store-link-props` throughout `orgit.el` fixes it, but i haven't tested it throughly.

**Comment by tarsius** [comment]
I believe installing both `org` and `org-plus-contrib` is wrong. But maybe you cannot get around that because some package declares `org` as a dependency but you actually want to use "org plus contrib". This is a limitation of `package.el`; it doesn't support alternatives.

`orgit` now depends on Org >= 9.3. **Every** timestamp "version" satisfies every version because e.g. `19700101 >= 9.3`. That is a limitation of Melpa, see https://github.com/melpa/melpa/issues/2955.

I.e. update to whatever snapshot version of Org that is *actually* "greater" than 9.3. Hm... Your Org version is from only two days ago?!

**Comment by xzz53** [comment]
Looks like i've messed up my `.emacs.d` (again). I'l try reinstalling everything from scratch later today and report if the issue persists.
